### ISSUE TITLE
rate of your project

### ISSUE THREAD

**Issue by bust6k** [HayKor/gocalc-api#3]
1.Readme файл- за то, что он на английском сразу снижаю наполовину, потому что есть люди которые не могут читать на инглише, тем более есть пара команд которые не работают(7/20)

2.Рабочий код- тут все прекрасно, и даже немного больше чем лицей ожидал, я бы поставил минимум бы 25,но из за ограничений (20/20)

3.Тесты- впринципе, тесты для парсера и лексера есть, но теста для тестирования самого веб сервиса нет, поэтому ставлю (15/20)

4.разбиение программы на пакеты- тут все прекрасно ,без комментариев (20/20)

5.Качество кода - тут особо придраться не к чему, поэтому (20/20)

**Comment by HayKor** [comment]
1) Какие команды не работают?

Спасибо за фидбек!!!

**Comment by HayKor** [comment]
> 1. ... тем более есть пара команд которые не работают(7/20)

Какие команды не работают?
Спасибо за фидбек!!!

**Comment by bust6k** [comment]
Команда копирования репозитория. У меня инсталяция не работает. Когда я
клонировал либо через полный url путь,либо через ssh ключ вот тогда твой
проект скопировался ко мне

ср, 25 дек. 2024 г., 09:09 Arthur Baginian ***@***.***>:

**Comment by HayKor** [comment]
Пофиксил
 #4

**Comment by bust6k** [comment]
Хорош,но за английский все равно выходит только 11 баллов за редми(до фикса
было 7)

ср, 25 дек. 2024 г., 11:44 Arthur Baginian ***@***.***>:

**Comment by bust6k** [comment]
У тебя 86 если что сейчас(было 82)

ср, 25 дек. 2024 г., 11:51 Ruslan ***@***.***>:

**Comment by bust6k** [comment]
Поздравляю,ты сдал егэ!

ср, 25 дек. 2024 г., 11:53 Ruslan ***@***.***>:
